Feature: Add Apple Books Highlight Links
bandantonio/obsidian-apple-books-highlights-plugin pull request #24
Opened 2024-07-08 02:31 UTC by absorpheus

**What is it?**

This feature will fetch the EPUB Canonical Fragment Identifier for highlights so that they can be opened at the exact highlight location with Apple Books.

**Summary**

* test(db): update migrations to enable new database tests

* test: add basic highlight links tests for db

* test: update mock tests, plugin docs and info

* refactor(core): update default template to include highlight location

* refactor(core): update types, constants, schemas, seedData and methods

* fix: template for colored highlights. register handlebars custom helpers. Minor grammar fixes

* docs(README): update preview and template-colors screenshots to show highlight links feature

* docs(README): add highlight location template variable

* docs(README): update template with highlight link

* linter: update tsconfig to remove unnecessary type checks

2024-07-08 17:15 UTC, bandantonio requested changes
@absorpheus Thank you for the contribution, the PR looks great.
However, I see multiple updates that you're trying to deliver:
- highlights link feature + tests and migrations
- fix for #25  (I will take care of that one, it needs tests to be fixed as well)
- fix for grammar 

I would recommend you to split this PR into two, each one containing the corresponding changes. Please use this repository directly (not a fork) to make those changes, because the required checks weren't triggered for some reason for the PR. I will investigate why.
Thank you.

2024-07-08 17:15 UTC, bandantonio commented on README.md
> +- 📙 Highlight Link:: {{#if highlightLocation}}[Apple Books Highlight Link](ibooks://assetid/{{../bookId}}#{{highlightLocation}}){{else}}N/A{{/if}}
```suggestion
- 📙 Highlight Link:: {{#if highlightLocation}}[Apple Books Highlight Link](ibooks://assetid/{{bookId}}#{{highlightLocation}}){{else}}N/A{{/if}}
```

2024-07-08 17:21 UTC, bandantonio commented on template-colors.png
I believe it's not necessary to add a highlight link to this template, as its main focus is on colors. So you can revert to the original screenshot.

2024-07-08 18:37 UTC, absorpheus commented
@bandantonio Thank you for your feedback on the PR. I will work on making these changes very soon.

2024-07-08 18:42 UTC, bandantonio commented
@absorpheus No worries, I just released a new version to fix the bug with custom templates, in order to prevent user experience disruption. So there is no rush, take your time, please.

2024-07-10 12:36 UTC, absorpheus commented
@bandantonio Please give me permission to access the repository so I can push the feature branches and create the PR's. Thank you

2024-07-16 18:07 UTC, bandantonio commented
This PR was split into several ones:
- highlights link feature + tests and migrations #27 
- fix for #25
- fix for grammar  #36

2024-07-16 18:07 UTC, closed without merging